#!/usr/bin/env node
/**
 * Airtable import — extraction.
 *
 * Pulls every table out of the base as JSON, keeping Airtable's record IDs so
 * relationships survive. That is the whole reason this is not a CSV export:
 * Airtable writes a linked record to CSV as its primary-field display text
 * ("GUA-0013 | Leerang Lim"), so rebuilding the joins would mean parsing names.
 *
 * Writes one .sql file that fills the staging schema. Nothing is transformed
 * here — that is 02-transform.sql's job, where it can be inspected and re-run.
 *
 * Usage:
 *   AIRTABLE_PAT=pat... node scripts/airtable-import/extract.mjs
 *
 * Optional:
 *   AIRTABLE_BASE=app...   default is the Jah Copy
 *   OUT=path/to/file.sql   default ./airtable-export/00-data.sql
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

const PAT = process.env.AIRTABLE_PAT;
const BASE = process.env.AIRTABLE_BASE ?? "appEobvB14kpW8hHw";
const OUT = process.env.OUT ?? "airtable-export/00-data.sql";

if (!PAT) {
  console.error(
    "AIRTABLE_PAT is not set.\n\n" +
      "Create a personal access token at https://airtable.com/create/tokens with\n" +
      "  scopes: data.records:read, schema.bases:read\n" +
      "  access: the base you are importing\n\n" +
      "Then:  AIRTABLE_PAT=pat... node scripts/airtable-import/extract.mjs",
  );
  process.exit(1);
}

/** Airtable table id → staging table. Ids are stable across base duplicates. */
const TABLES = [
  ["tblsrGS7YO853AOJQ", "at_guardians", "Parents / Guardians"],
  ["tblGEBWI2Qnx9ciHR", "at_students", "Students"],
  ["tblIjhJA3gvKlsB3I", "at_tutors", "Tutors"],
  ["tblIZAtiMlMseEi2A", "at_periods", "Operating Periods"],
  ["tblxOt60GEloV59gt", "at_prices", "Standard Prices"],
  ["tblFI2YU4f5sHNA9v", "at_programs", "Programs"],
  ["tblRSHQ5AQztcUYor", "at_offerings", "Class Offerings"],
  ["tblJvhEcxeS9BXRjH", "at_billing", "Billing"],
  ["tbl2sQ1iO5vfQy9VS", "at_hours", "Hours"],
  ["tblpAeJ1PV7DDgsRO", "at_sessions", "Sessions"],
  ["tblsRWT3ZJQRnoKhg", "at_attendance", "Attendance"],
  ["tblbx2atoGVPazVOQ", "at_charges", "Charges"],
  ["tblkHQ920Ap6CuU7l", "at_payouts", "Tutor Payouts"],
];

async function fetchAll(tableId, label) {
  const rows = [];
  let offset;

  do {
    const url = new URL(`https://api.airtable.com/v0/${BASE}/${tableId}`);
    url.searchParams.set("pageSize", "100");
    if (offset) url.searchParams.set("offset", offset);

    const res = await fetch(url, { headers: { Authorization: `Bearer ${PAT}` } });

    if (res.status === 429) {
      // Airtable allows 5 requests/second per base. Back off and retry.
      await new Promise((r) => setTimeout(r, 1500));
      continue;
    }
    if (!res.ok) {
      throw new Error(`${label}: ${res.status} ${res.statusText}\n${await res.text()}`);
    }

    const body = await res.json();
    rows.push(...body.records);
    offset = body.offset;
    await new Promise((r) => setTimeout(r, 220)); // stay under the rate limit
  } while (offset);

  console.error(`  ${label.padEnd(22)} ${String(rows.length).padStart(5)}`);
  return rows;
}

/** Single-quote escaping for a SQL string literal. */
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

console.error(`Extracting from ${BASE}\n`);

const out = [
  "-- Generated by scripts/airtable-import/extract.mjs. Do not edit.",
  `-- Base ${BASE} · extracted ${new Date().toISOString()}`,
  "--",
  "-- Contains real student and guardian data. Do NOT commit this file.",
  "",
  "begin;",
  "",
];

let total = 0;
for (const [tableId, stagingTable, label] of TABLES) {
  const records = await fetchAll(tableId, label);
  total += records.length;

  out.push(`-- ${label} → staging.${stagingTable} (${records.length})`);
  out.push(`truncate staging.${stagingTable};`);

  for (const r of records) {
    out.push(
      `insert into staging.${stagingTable} (id, created_time, fields) values ` +
        `(${q(r.id)}, ${q(r.createdTime)}, ${q(JSON.stringify(r.fields))}::jsonb);`,
    );
  }
  out.push("");
}

out.push("commit;");

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, out.join("\n"));

console.error(`\n${total} records → ${OUT}`);
console.error("\nNext:");
console.error("  psql \"$DATABASE_URL\" -f scripts/airtable-import/01-staging.sql");
console.error(`  psql "$DATABASE_URL" -f ${OUT}`);
console.error("  psql \"$DATABASE_URL\" -f scripts/airtable-import/02-transform.sql");
console.error("  psql \"$DATABASE_URL\" -f scripts/airtable-import/03-verify.sql");
