#!/usr/bin/env node
/**
 * Airtable import — extraction, without a personal access token.
 *
 * extract.mjs is the better path: give it a PAT and it pulls the base itself.
 * This is the fallback for when the only read access available is through the
 * Airtable connector, which hands back pages of JSON rather than a stream.
 *
 * Feed it those pages verbatim — one file per page, named
 * <staging table>.<page>.json — and it produces exactly the file extract.mjs
 * produces. Nothing is retyped by hand, so a corrupted page fails as a JSON
 * parse error rather than as a plausible wrong value that survives to Postgres.
 *
 * The connector's shape differs from the raw API's in three ways, all handled
 * below: cells are keyed by field ID, single selects arrive as objects, and
 * linked records arrive as {id, name} pairs where the import wants bare IDs.
 *
 * Usage:
 *   node scripts/airtable-import/from-mcp.mjs [pagesDir] [outFile]
 *
 * Defaults: airtable-export/pages → airtable-export/00-data.sql
 */

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const PAGES = process.argv[2] ?? "airtable-export/pages";
const OUT = process.argv[3] ?? "airtable-export/00-data.sql";

/** Staging table → label, in the dependency order 02-transform.sql expects. */
const TABLES = [
  ["at_guardians", "Parents / Guardians"],
  ["at_students", "Students"],
  ["at_tutors", "Tutors"],
  ["at_periods", "Operating Periods"],
  ["at_prices", "Standard Prices"],
  ["at_programs", "Programs"],
  ["at_offerings", "Class Offerings"],
  ["at_billing", "Billing"],
  ["at_hours", "Hours"],
  ["at_sessions", "Sessions"],
  ["at_attendance", "Attendance"],
  ["at_charges", "Charges"],
  ["at_payouts", "Tutor Payouts"],
];

/**
 * The connector returns select choices and linked records as objects. The
 * import reads a select as its name and a link as its record ID, so the shape
 * is decided by what the ids inside it look like rather than by a schema file
 * that could fall out of step with the base.
 */
function normalise(value) {
  if (value === null || value === undefined) return value;

  if (Array.isArray(value)) {
    const out = value.map(normalise).filter((v) => v !== null && v !== undefined);
    return out.length ? out : undefined;
  }

  if (typeof value === "object") {
    if (typeof value.id === "string" && value.id.startsWith("rec")) return value.id;
    if (typeof value.name === "string") return value.name;   // sel..., usr...
    return value;                                             // attachments etc.
  }

  if (typeof value === "string" && value.trim() === "") return undefined;
  return value;
}

/** Cells keyed by field ID → cells keyed by field name. */
function byName(cells, fieldNames, label) {
  const fields = {};
  for (const [fieldId, raw] of Object.entries(cells ?? {})) {
    const name = fieldNames[fieldId];
    if (!name) throw new Error(`${label}: no name known for field ${fieldId}`);
    const value = normalise(raw);
    if (value !== undefined) fields[name] = value;
  }
  return fields;
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const files = (await readdir(PAGES)).filter((f) => f.endsWith(".json")).sort();

/**
 * fields.json maps every field ID in the base to its name. Written once from
 * the connector's base summary; without it the pages are unreadable, since
 * every cell is keyed by ID.
 */
const fieldNames = JSON.parse(await readFile(join(PAGES, "fields.json"), "utf8"));

const out = [
  "-- Generated by scripts/airtable-import/from-mcp.mjs. Do not edit.",
  "-- Contains real student and guardian data. Do NOT commit this file.",
  "",
  "begin;",
  "",
];

let total = 0;
const counts = [];

for (const [stagingTable, label] of TABLES) {
  const pages = files.filter((f) => f.startsWith(`${stagingTable}.`));
  if (!pages.length) {
    throw new Error(`no pages found for ${stagingTable} in ${PAGES}`);
  }

  const records = [];
  const seen = new Set();
  let expected = null;

  for (const page of pages) {
    const body = JSON.parse(await readFile(join(PAGES, page), "utf8"));
    if (body.metadata?.totalRecordCount != null) {
      expected = body.metadata.totalRecordCount;
    }
    for (const r of body.records ?? []) {
      // Pages can overlap when a cursor is replayed. Last write wins; the
      // record ID is the identity either way.
      if (seen.has(r.id)) continue;
      seen.add(r.id);
      records.push(r);
    }
  }

  if (expected !== null && records.length !== expected) {
    throw new Error(
      `${label}: have ${records.length} records but the base reports ${expected}. ` +
        `A page is missing — re-pull from the last cursor.`,
    );
  }

  out.push(`-- ${label} → staging.${stagingTable} (${records.length})`);
  out.push(`truncate staging.${stagingTable};`);
  for (const r of records) {
    const fields = byName(r.cellValuesByFieldId ?? r.fields, fieldNames, label);
    out.push(
      `insert into staging.${stagingTable} (id, created_time, fields) values ` +
        `(${q(r.id)}, ${q(r.createdTime)}, ${q(JSON.stringify(fields))}::jsonb);`,
    );
  }
  out.push("");

  counts.push(`  ${label.padEnd(22)} ${String(records.length).padStart(5)}`);
  total += records.length;
}

out.push("commit;");

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, out.join("\n"));

console.error(counts.join("\n"));
console.error(`\n${total} records → ${OUT}`);
