/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedEnrolmentsRouteImport } from './routes/_authenticated/enrolments'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedNeedsAttentionRouteImport } from './routes/_authenticated/needs-attention'
import { Route as AuthenticatedRollRouteImport } from './routes/_authenticated/roll'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTutorPayRouteImport } from './routes/_authenticated/tutor-pay'
import { Route as AuthenticatedTutorsRouteImport } from './routes/_authenticated/tutors'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes.index'
import { Route as AuthenticatedClassesNewRouteImport } from './routes/_authenticated/classes.new'
import { Route as AuthenticatedPrototypeDashboardRouteImport } from './routes/_authenticated/prototype.dashboard'
import { Route as AuthenticatedPrototypePackagesRouteImport } from './routes/_authenticated/prototype.packages'
import { Route as AuthenticatedPrototypeSessionsRouteImport } from './routes/_authenticated/prototype.sessions'
import { Route as AuthenticatedPrototypeStudentsRouteImport } from './routes/_authenticated/prototype.students'
import { Route as AuthenticatedPrototypeTutorsRouteImport } from './routes/_authenticated/prototype.tutors'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedPrototypeStudentsIdRouteImport } from './routes/_authenticated/prototype.students.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnrolmentsRoute = AuthenticatedEnrolmentsRouteImport.update({
  id: '/enrolments',
  path: '/enrolments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNeedsAttentionRoute =
  AuthenticatedNeedsAttentionRouteImport.update({
    id: '/needs-attention',
    path: '/needs-attention',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRollRoute = AuthenticatedRollRouteImport.update({
  id: '/roll',
  path: '/roll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorPayRoute = AuthenticatedTutorPayRouteImport.update({
  id: '/tutor-pay',
  path: '/tutor-pay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorsRoute = AuthenticatedTutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesNewRoute = AuthenticatedClassesNewRouteImport.update({
  id: '/classes/new',
  path: '/classes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrototypeDashboardRoute =
  AuthenticatedPrototypeDashboardRouteImport.update({
    id: '/prototype/dashboard',
    path: '/prototype/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrototypePackagesRoute =
  AuthenticatedPrototypePackagesRouteImport.update({
    id: '/prototype/packages',
    path: '/prototype/packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrototypeSessionsRoute =
  AuthenticatedPrototypeSessionsRouteImport.update({
    id: '/prototype/sessions',
    path: '/prototype/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrototypeStudentsRoute =
  AuthenticatedPrototypeStudentsRouteImport.update({
    id: '/prototype/students',
    path: '/prototype/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrototypeTutorsRoute =
  AuthenticatedPrototypeTutorsRouteImport.update({
    id: '/prototype/tutors',
    path: '/prototype/tutors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrototypeStudentsIdRoute =
  AuthenticatedPrototypeStudentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPrototypeStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/enrolments': typeof AuthenticatedEnrolmentsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/needs-attention': typeof AuthenticatedNeedsAttentionRoute
  '/roll': typeof AuthenticatedRollRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/today': typeof AuthenticatedTodayRoute
  '/tutor-pay': typeof AuthenticatedTutorPayRoute
  '/tutors': typeof AuthenticatedTutorsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/prototype/dashboard': typeof AuthenticatedPrototypeDashboardRoute
  '/prototype/packages': typeof AuthenticatedPrototypePackagesRoute
  '/prototype/sessions': typeof AuthenticatedPrototypeSessionsRoute
  '/prototype/students': typeof AuthenticatedPrototypeStudentsRouteWithChildren
  '/prototype/tutors': typeof AuthenticatedPrototypeTutorsRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/prototype/students/$id': typeof AuthenticatedPrototypeStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/enrolments': typeof AuthenticatedEnrolmentsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/needs-attention': typeof AuthenticatedNeedsAttentionRoute
  '/roll': typeof AuthenticatedRollRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/today': typeof AuthenticatedTodayRoute
  '/tutor-pay': typeof AuthenticatedTutorPayRoute
  '/tutors': typeof AuthenticatedTutorsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/classes/new': typeof AuthenticatedClassesNewRoute
  '/prototype/dashboard': typeof AuthenticatedPrototypeDashboardRoute
  '/prototype/packages': typeof AuthenticatedPrototypePackagesRoute
  '/prototype/sessions': typeof AuthenticatedPrototypeSessionsRoute
  '/prototype/students': typeof AuthenticatedPrototypeStudentsRouteWithChildren
  '/prototype/tutors': typeof AuthenticatedPrototypeTutorsRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/prototype/students/$id': typeof AuthenticatedPrototypeStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/enrolments': typeof AuthenticatedEnrolmentsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/needs-attention': typeof AuthenticatedNeedsAttentionRoute
  '/_authenticated/roll': typeof AuthenticatedRollRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/tutor-pay': typeof AuthenticatedTutorPayRoute
  '/_authenticated/tutors': typeof AuthenticatedTutorsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/classes/new': typeof AuthenticatedClassesNewRoute
  '/_authenticated/prototype/dashboard': typeof AuthenticatedPrototypeDashboardRoute
  '/_authenticated/prototype/packages': typeof AuthenticatedPrototypePackagesRoute
  '/_authenticated/prototype/sessions': typeof AuthenticatedPrototypeSessionsRoute
  '/_authenticated/prototype/students': typeof AuthenticatedPrototypeStudentsRouteWithChildren
  '/_authenticated/prototype/tutors': typeof AuthenticatedPrototypeTutorsRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/prototype/students/$id': typeof AuthenticatedPrototypeStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing'
    | '/enrolments'
    | '/leads'
    | '/needs-attention'
    | '/roll'
    | '/setup'
    | '/staff'
    | '/timetable'
    | '/today'
    | '/tutor-pay'
    | '/tutors'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/classes/new'
    | '/prototype/dashboard'
    | '/prototype/packages'
    | '/prototype/sessions'
    | '/prototype/students'
    | '/prototype/tutors'
    | '/students/$id'
    | '/classes/'
    | '/students/'
    | '/prototype/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing'
    | '/enrolments'
    | '/leads'
    | '/needs-attention'
    | '/roll'
    | '/setup'
    | '/staff'
    | '/timetable'
    | '/today'
    | '/tutor-pay'
    | '/tutors'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/classes/new'
    | '/prototype/dashboard'
    | '/prototype/packages'
    | '/prototype/sessions'
    | '/prototype/students'
    | '/prototype/tutors'
    | '/students/$id'
    | '/classes'
    | '/students'
    | '/prototype/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/billing'
    | '/_authenticated/enrolments'
    | '/_authenticated/leads'
    | '/_authenticated/needs-attention'
    | '/_authenticated/roll'
    | '/_authenticated/setup'
    | '/_authenticated/staff'
    | '/_authenticated/timetable'
    | '/_authenticated/today'
    | '/_authenticated/tutor-pay'
    | '/_authenticated/tutors'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/classes/new'
    | '/_authenticated/prototype/dashboard'
    | '/_authenticated/prototype/packages'
    | '/_authenticated/prototype/sessions'
    | '/_authenticated/prototype/students'
    | '/_authenticated/prototype/tutors'
    | '/_authenticated/students/$id'
    | '/_authenticated/classes/'
    | '/_authenticated/students/'
    | '/_authenticated/prototype/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessRoute: typeof AccessRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enrolments': {
      id: '/_authenticated/enrolments'
      path: '/enrolments'
      fullPath: '/enrolments'
      preLoaderRoute: typeof AuthenticatedEnrolmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/needs-attention': {
      id: '/_authenticated/needs-attention'
      path: '/needs-attention'
      fullPath: '/needs-attention'
      preLoaderRoute: typeof AuthenticatedNeedsAttentionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roll': {
      id: '/_authenticated/roll'
      path: '/roll'
      fullPath: '/roll'
      preLoaderRoute: typeof AuthenticatedRollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor-pay': {
      id: '/_authenticated/tutor-pay'
      path: '/tutor-pay'
      fullPath: '/tutor-pay'
      preLoaderRoute: typeof AuthenticatedTutorPayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutors': {
      id: '/_authenticated/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof AuthenticatedTutorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/new': {
      id: '/_authenticated/classes/new'
      path: '/classes/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof AuthenticatedClassesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prototype/dashboard': {
      id: '/_authenticated/prototype/dashboard'
      path: '/prototype/dashboard'
      fullPath: '/prototype/dashboard'
      preLoaderRoute: typeof AuthenticatedPrototypeDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prototype/packages': {
      id: '/_authenticated/prototype/packages'
      path: '/prototype/packages'
      fullPath: '/prototype/packages'
      preLoaderRoute: typeof AuthenticatedPrototypePackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prototype/sessions': {
      id: '/_authenticated/prototype/sessions'
      path: '/prototype/sessions'
      fullPath: '/prototype/sessions'
      preLoaderRoute: typeof AuthenticatedPrototypeSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prototype/students': {
      id: '/_authenticated/prototype/students'
      path: '/prototype/students'
      fullPath: '/prototype/students'
      preLoaderRoute: typeof AuthenticatedPrototypeStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prototype/tutors': {
      id: '/_authenticated/prototype/tutors'
      path: '/prototype/tutors'
      fullPath: '/prototype/tutors'
      preLoaderRoute: typeof AuthenticatedPrototypeTutorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prototype/students/$id': {
      id: '/_authenticated/prototype/students/$id'
      path: '/$id'
      fullPath: '/prototype/students/$id'
      preLoaderRoute: typeof AuthenticatedPrototypeStudentsIdRouteImport
      parentRoute: typeof AuthenticatedPrototypeStudentsRoute
    }
  }
}

interface AuthenticatedPrototypeStudentsRouteChildren {
  AuthenticatedPrototypeStudentsIdRoute: typeof AuthenticatedPrototypeStudentsIdRoute
}

const AuthenticatedPrototypeStudentsRouteChildren: AuthenticatedPrototypeStudentsRouteChildren =
  {
    AuthenticatedPrototypeStudentsIdRoute:
      AuthenticatedPrototypeStudentsIdRoute,
  }

const AuthenticatedPrototypeStudentsRouteWithChildren =
  AuthenticatedPrototypeStudentsRoute._addFileChildren(
    AuthenticatedPrototypeStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedEnrolmentsRoute: typeof AuthenticatedEnrolmentsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNeedsAttentionRoute: typeof AuthenticatedNeedsAttentionRoute
  AuthenticatedRollRoute: typeof AuthenticatedRollRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTutorPayRoute: typeof AuthenticatedTutorPayRoute
  AuthenticatedTutorsRoute: typeof AuthenticatedTutorsRoute
  AuthenticatedClassesNewRoute: typeof AuthenticatedClassesNewRoute
  AuthenticatedPrototypeDashboardRoute: typeof AuthenticatedPrototypeDashboardRoute
  AuthenticatedPrototypePackagesRoute: typeof AuthenticatedPrototypePackagesRoute
  AuthenticatedPrototypeSessionsRoute: typeof AuthenticatedPrototypeSessionsRoute
  AuthenticatedPrototypeStudentsRoute: typeof AuthenticatedPrototypeStudentsRouteWithChildren
  AuthenticatedPrototypeTutorsRoute: typeof AuthenticatedPrototypeTutorsRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedEnrolmentsRoute: AuthenticatedEnrolmentsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNeedsAttentionRoute: AuthenticatedNeedsAttentionRoute,
  AuthenticatedRollRoute: AuthenticatedRollRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTutorPayRoute: AuthenticatedTutorPayRoute,
  AuthenticatedTutorsRoute: AuthenticatedTutorsRoute,
  AuthenticatedClassesNewRoute: AuthenticatedClassesNewRoute,
  AuthenticatedPrototypeDashboardRoute: AuthenticatedPrototypeDashboardRoute,
  AuthenticatedPrototypePackagesRoute: AuthenticatedPrototypePackagesRoute,
  AuthenticatedPrototypeSessionsRoute: AuthenticatedPrototypeSessionsRoute,
  AuthenticatedPrototypeStudentsRoute:
    AuthenticatedPrototypeStudentsRouteWithChildren,
  AuthenticatedPrototypeTutorsRoute: AuthenticatedPrototypeTutorsRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessRoute: AccessRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
