-- =============================================================================
-- Leads & Trials — the pre-student pipeline.
--
-- Everything upstream of guardian → student. A `lead` is an enquiry; every time
-- we reach out is a `lead_contact`; a `trial` is a booked class trial or a
-- bespoke diagnostic, pointing at the real class_offering / session that
-- delivers it. On conversion a lead names the student and trial enrolment it
-- became, and the existing enrolment / session / attendance machinery takes
-- over — nothing here duplicates it.
--
-- Follows the conventions in docs/spec/03-schema.sql: uuid keys, a generated
-- human `code`, airtable_id for reconciliation, a touch trigger, facts only —
-- anything derived lives in v_leads.
-- =============================================================================

-- =============================================================================
-- 1. ENUMS
-- =============================================================================

create type lead_status     as enum ('new', 'contacted', 'nurturing', 'trial_booked', 'converted', 'lost');
create type lead_source     as enum ('referral', 'google', 'social_media', 'walk_in', 'event', 'website', 'other');
create type contact_channel as enum ('phone', 'sms', 'email', 'whatsapp', 'in_person', 'other');
create type trial_kind      as enum ('class_trial', 'diagnostic_test');
create type trial_status    as enum ('proposed', 'scheduled', 'attended', 'no_show', 'converted', 'declined');
create type diagnostic_recommendation as enum
  ('ready_for_class', 'needs_foundation', 'accelerate', 'not_suitable', 'undecided');

-- =============================================================================
-- 2. LEADS
-- =============================================================================

create table leads (
  id                     uuid primary key default gen_random_uuid(),
  seq                    bigint generated by default as identity,
  code                   text generated always as ('LEAD-' || lpad(seq::text, 4, '0')) stored,
  -- the child being enquired about; no student record exists yet, so free text
  student_name           text        not null,
  year_level             text,
  subject_interest       text,
  program_interest_id    uuid        references programs(id) on delete set null,
  -- the enquiring parent
  guardian_name          text        not null,
  guardian_email         text,
  guardian_mobile        text,
  -- pipeline
  status                 lead_status not null default 'new',
  source                 lead_source not null default 'other',
  source_detail          text,
  assigned_to            uuid        references staff(user_id) on delete set null,
  next_action_on         date,
  lost_reason            text,
  -- conversion outcome (set when status = 'converted')
  converted_student_id   uuid        references students(id) on delete set null,
  converted_enrolment_id uuid        references enrolments(id) on delete set null,
  converted_at           timestamptz,
  notes                  text,
  airtable_id            text unique,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  -- Mirrors the project's "adjustments need a written reason" stance.
  constraint lead_lost_needs_reason
    check (status <> 'lost' or (lost_reason is not null and length(btrim(lost_reason)) > 0)),
  -- Can't mark a lead converted without pointing at the student it became.
  constraint lead_converted_needs_student
    check (status <> 'converted' or converted_student_id is not null)
);
create unique index leads_code_key on leads (code);
create index leads_status_idx    on leads (status);
create index leads_assigned_idx  on leads (assigned_to);
create index leads_next_action_idx on leads (next_action_on);
create trigger leads_touch before update on leads
  for each row execute function set_updated_at();

-- =============================================================================
-- 3. LEAD CONTACTS  — the log of "when we've contacted them"
-- =============================================================================

create table lead_contacts (
  id             uuid            primary key default gen_random_uuid(),
  lead_id        uuid            not null references leads(id) on delete cascade,
  contacted_at   timestamptz     not null default now(),
  channel        contact_channel not null,
  summary        text            not null check (length(btrim(summary)) > 0),
  next_action_on date,
  contacted_by   uuid            references staff(user_id) on delete set null,
  created_at     timestamptz     not null default now()
);
create index lead_contacts_lead_idx on lead_contacts (lead_id, contacted_at desc);

-- =============================================================================
-- 4. TRIALS  — a booked class trial or bespoke diagnostic for a lead
-- =============================================================================

create table trials (
  id                     uuid         primary key default gen_random_uuid(),
  seq                    bigint generated by default as identity,
  code                   text generated always as ('TRL-' || lpad(seq::text, 4, '0')) stored,
  lead_id                uuid         not null references leads(id) on delete cascade,
  kind                   trial_kind   not null default 'class_trial',
  -- where it happens. "Making a new trial class" is just creating an offering
  -- and pointing here; session_id names the specific lesson when known.
  class_offering_id      uuid         references class_offerings(id) on delete set null,
  session_id             uuid         references sessions(id) on delete set null,
  -- once the lead becomes a student, the trial enrolment that delivers it
  enrolment_id           uuid         references enrolments(id) on delete set null,
  scheduled_for          timestamptz,
  status                 trial_status not null default 'proposed',
  -- diagnostic outcome
  recommendation         diagnostic_recommendation,
  recommended_program_id uuid         references programs(id) on delete set null,
  score                  text,        -- free text: diagnostics vary too much to type
  outcome_notes          text,
  conducted_by           uuid         references tutors(id) on delete set null,
  airtable_id            text unique,
  created_at             timestamptz  not null default now(),
  updated_at             timestamptz  not null default now(),
  constraint trial_class_needs_offering
    check (kind <> 'class_trial' or class_offering_id is not null)
);
create unique index trials_code_key    on trials (code);
create index trials_lead_idx     on trials (lead_id);
create index trials_offering_idx on trials (class_offering_id);
create trigger trials_touch before update on trials
  for each row execute function set_updated_at();

-- =============================================================================
-- 5. VIEW  — the pipeline board reads this, so nothing derived is stored
-- =============================================================================

create or replace view v_leads
with (security_invoker = true) as
  select
    l.*,
    lc.latest_contact_at,
    coalesce(lc.contact_count, 0)                        as contact_count,
    case when lc.latest_contact_at is not null
         then syd_date(now()) - syd_date(lc.latest_contact_at) end as days_since_contact,
    syd_date(now()) - syd_date(l.created_at)             as days_in_pipeline,
    coalesce(tr.trial_count, 0)                          as trial_count,
    (l.next_action_on is not null
       and l.next_action_on < syd_date(now())
       and l.status not in ('converted', 'lost'))        as is_overdue,
    s.full_name                                          as assigned_name,
    p.name                                               as program_interest_name
  from leads l
  left join (
    select lead_id, max(contacted_at) as latest_contact_at, count(*) as contact_count
    from lead_contacts group by lead_id
  ) lc on lc.lead_id = l.id
  left join (
    select lead_id, count(*) as trial_count from trials group by lead_id
  ) tr on tr.lead_id = l.id
  left join staff    s on s.user_id = l.assigned_to
  left join programs p on p.id = l.program_interest_id;

-- =============================================================================
-- 6. ROW LEVEL SECURITY  — operational data: any active staff member
-- =============================================================================

alter table leads         enable row level security;
alter table lead_contacts enable row level security;
alter table trials        enable row level security;

do $$
declare t text;
begin
  foreach t in array array['leads', 'lead_contacts', 'trials'] loop
    execute format('create policy %I_staff_all on public.%I for all to authenticated
                    using (is_staff()) with check (is_staff())', t, t);
  end loop;
end $$;

-- =============================================================================
-- 7. GRANTS  — RLS decides which rows; grants decide table reach. Both needed.
-- =============================================================================

do $$
declare t text;
begin
  foreach t in array array['leads', 'lead_contacts', 'trials'] loop
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('grant all on public.%I to service_role', t);
  end loop;
end $$;

grant select on public.v_leads to authenticated, service_role;
