-- =============================================================================
-- Billing: give an invoice its own identity.
--
-- Charges could already be sent out together - markInvoiced stamped a set of
-- them with one date and one Xero number - but nothing recorded that they were
-- one invoice. The only thing tying them together was that optional number, and
-- it is genuinely optional: a family invoiced without one left five charges
-- that had been sent as a single bill and no way to tell.
--
-- So the unpaid queue showed five separate lines for what the family received
-- as one document, and there was no way to open the invoice and see what was on
-- it.
--
-- An invoice is now a row. It is created when a run goes out, carries its own
-- INV- code the way every other record here does, and the charges on it point
-- at it. The Xero number stays what it has always been: the reference to the
-- document in the accounting system, filled in when there is one.
-- =============================================================================

create table if not exists invoices (
  id              uuid primary key default gen_random_uuid(),
  seq             bigint generated by default as identity,
  invoice_year    int not null default extract(year from (now() at time zone 'Australia/Sydney'))::int,
  code            text generated always as
                    ('INV-' || invoice_year::text || '-' || lpad(seq::text, 4, '0')) stored,
  -- Who the bill went to. Null for an internally routed run, which is nobody's
  -- invoice but still one run.
  payer_id        uuid references guardians(id) on delete restrict,
  invoice_date    date not null,
  method          payment_method,
  xero_invoice_no text,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists invoices_payer_idx on invoices (payer_id);
create index if not exists invoices_date_idx  on invoices (invoice_date desc);

-- A charge belongs to at most one invoice. Deleting an invoice must never take
-- the charge with it - the money asked for is the record, the invoice is the
-- document - so this is SET NULL and the charge falls back to being its own
-- line.
alter table charges add column if not exists invoice_id uuid
  references invoices(id) on delete set null;

create index if not exists charges_invoice_idx on charges (invoice_id);

alter table invoices enable row level security;

drop policy if exists invoices_staff_all on invoices;
create policy invoices_staff_all on invoices for all to authenticated
  using (is_staff()) with check (is_staff());

grant select, insert, update, delete on public.invoices to authenticated;
grant all on public.invoices to service_role;

-- ---------------------------------------------------------------------------
-- Backfill.
--
-- Everything already invoiced was sent as some run, and the evidence of which
-- run is still there: charges that went out together share a payer, a date, a
-- method and a Xero number. Grouping on exactly those four reconstructs the
-- invoices that were actually sent, so history reads the way the families
-- received it rather than starting empty from today.
--
-- Two runs to the same family, on the same day, by the same method, both
-- without a number, merge into one. That is the one case this cannot tell
-- apart, and it is the same information a person reading the old screen had.
-- ---------------------------------------------------------------------------

do $$
declare r record;
        v_invoice uuid;
begin
  for r in
    select c.payer_id,
           c.invoice_date,
           c.method,
           coalesce(c.xero_invoice_no, '') as xero_no
    from charges c
    where c.invoice_id is null
      and c.invoice_date is not null
      and c.status in ('invoiced', 'paid')
    group by 1, 2, 3, 4
  loop
    insert into invoices (payer_id, invoice_date, method, xero_invoice_no)
    values (r.payer_id, r.invoice_date, r.method, nullif(r.xero_no, ''))
    returning id into v_invoice;

    update charges c
       set invoice_id = v_invoice
     where c.invoice_id is null
       and c.invoice_date = r.invoice_date
       and c.status in ('invoiced', 'paid')
       and c.payer_id is not distinct from r.payer_id
       and c.method is not distinct from r.method
       and coalesce(c.xero_invoice_no, '') = r.xero_no;
  end loop;
end $$;
