create table if not exists invoices (
  id              uuid primary key default gen_random_uuid(),
  seq             bigint generated by default as identity,
  invoice_year    int not null default extract(year from (now() at time zone 'Australia/Sydney'))::int,
  code            text generated always as
                    ('INV-' || invoice_year::text || '-' || lpad(seq::text, 4, '0')) stored,
  payer_id        uuid references guardians(id) on delete restrict,
  invoice_date    date not null,
  method          payment_method,
  xero_invoice_no text,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists invoices_payer_idx on invoices (payer_id);
create index if not exists invoices_date_idx  on invoices (invoice_date desc);

alter table charges add column if not exists invoice_id uuid
  references invoices(id) on delete set null;
create index if not exists charges_invoice_idx on charges (invoice_id);

alter table invoices enable row level security;
drop policy if exists invoices_staff_all on invoices;
create policy invoices_staff_all on invoices for all to authenticated
  using (is_staff()) with check (is_staff());

grant select, insert, update, delete on public.invoices to authenticated;
grant all on public.invoices to service_role;

do $$
declare r record;
        v_invoice uuid;
begin
  for r in
    select c.payer_id,
           c.invoice_date,
           c.method,
           coalesce(c.xero_invoice_no, '') as xero_no
    from charges c
    where c.invoice_id is null
      and c.invoice_date is not null
      and c.status in ('invoiced', 'paid')
    group by 1, 2, 3, 4
  loop
    insert into invoices (payer_id, invoice_date, method, xero_invoice_no)
    values (r.payer_id, r.invoice_date, r.method, nullif(r.xero_no, ''))
    returning id into v_invoice;

    update charges c
       set invoice_id = v_invoice
     where c.invoice_id is null
       and c.invoice_date = r.invoice_date
       and c.status in ('invoiced', 'paid')
       and c.payer_id is not distinct from r.payer_id
       and c.method is not distinct from r.method
       and coalesce(c.xero_invoice_no, '') = r.xero_no;
  end loop;
end $$;