-- 1. Airtable identity + row sequence columns needed by the import
do $$
declare t text;
begin
  foreach t in array array[
    'guardians','students','tutors','operating_periods','standard_prices',
    'programs','class_offerings','enrolments','hours_packages','sessions',
    'attendance','charges'
  ] loop
    if to_regclass('public.' || t) is null then continue; end if;
    execute format('alter table public.%I add column if not exists airtable_id text', t);
    execute format('create unique index if not exists %I on public.%I (airtable_id)', t || '_airtable_id_key', t);
  end loop;

  foreach t in array array[
    'guardians','students','tutors','class_offerings','enrolments','hours_packages',
    'sessions','attendance','charges','tutor_payouts'
  ] loop
    if to_regclass('public.' || t) is null then continue; end if;
    execute format('alter table public.%I add column if not exists seq bigint generated by default as identity', t);
  end loop;
end $$;

-- 2. Raw import landing table (service-role only)
create table if not exists public.at_raw (
  tbl          text not null,
  id           text primary key,
  created_time timestamptz,
  fields       jsonb not null
);
alter table public.at_raw enable row level security;
grant all on public.at_raw to service_role;

-- 3. Staging schema: helpers + one view per Airtable table over at_raw
drop schema if exists staging cascade;
create schema staging;

create or replace function staging.link1(f jsonb, key text) returns text
language sql immutable as $$ select nullif(f -> key ->> 0, '') $$;
create or replace function staging.txt(f jsonb, key text) returns text
language sql immutable as $$ select nullif(btrim(coalesce(f ->> key, '')), '') $$;
create or replace function staging.num(f jsonb, key text) returns numeric
language sql immutable as $$ select nullif(btrim(coalesce(f ->> key, '')), '')::numeric $$;
create or replace function staging.dt(f jsonb, key text) returns date
language sql immutable as $$ select nullif(btrim(coalesce(f ->> key, '')), '')::date $$;
create or replace function staging.ts(f jsonb, key text) returns timestamptz
language sql immutable as $$ select nullif(btrim(coalesce(f ->> key, '')), '')::timestamptz $$;

do $$
declare t text;
begin
  foreach t in array array[
    'at_guardians','at_students','at_tutors','at_periods','at_prices','at_programs',
    'at_offerings','at_billing','at_hours','at_sessions','at_attendance','at_charges','at_payouts'
  ] loop
    execute format(
      'create view staging.%I as select id, created_time, fields from public.at_raw where tbl = %L',
      t, t);
  end loop;
end $$;