-- =============================================================================
-- Billing: a charge that is not tied to a lesson or a package.
--
-- Every charge until now had to hang off exactly one of two things - an
-- attendance row (PAYG) or an hours package - enforced by the charge_one_source
-- check. That is the right default: it is what makes double-billing impossible.
--
-- But it also means there is no way to bill a family for anything else. A
-- resource fee, a catch-up arranged off the timetable, a deposit taken before
-- the class exists, an adjustment agreed on the phone: all of them have a
-- student and an amount and nothing to point at, so none of them could be
-- raised at all.
--
-- 'manual' is that third kind. It carries neither a package nor an attendance,
-- so it can never collide with the two unique indexes that stop a lesson or a
-- package being billed twice.
--
-- ADD VALUE has to run on its own - the new label cannot be referenced by
-- another statement until the transaction that adds it has committed - so the
-- constraint that uses it is the next migration. IF NOT EXISTS makes this safe
-- to re-run.
-- =============================================================================

alter type charge_source add value if not exists 'manual';
