import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import { Check, Mountain } from "lucide-react";

import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

import { cn } from "@/lib/utils";

import sonoma from "@/assets/environments/sonoma.jpg.asset.json";
import sonomaThumb from "@/assets/environments/sonoma-thumb.jpg.asset.json";
import ventura from "@/assets/environments/ventura.jpg.asset.json";
import venturaThumb from "@/assets/environments/ventura-thumb.jpg.asset.json";
import mavericks from "@/assets/environments/mavericks.jpg.asset.json";
import mavericksThumb from "@/assets/environments/mavericks-thumb.jpg.asset.json";
import elCapitan from "@/assets/environments/yosemite2.jpg.asset.json";
import elCapitanThumb from "@/assets/environments/yosemite2-thumb.jpg.asset.json";
import bigSur from "@/assets/environments/vestrahorn.jpg.asset.json";
import bigSurThumb from "@/assets/environments/vestrahorn-thumb.jpg.asset.json";
import catalina from "@/assets/environments/yosemite.jpg.asset.json";
import catalinaThumb from "@/assets/environments/yosemite-thumb.jpg.asset.json";
import sierra from "@/assets/environments/vernazza.jpg.asset.json";
import sierraThumb from "@/assets/environments/vernazza-thumb.jpg.asset.json";
import mojave from "@/assets/environments/vermilion.jpg.asset.json";
import mojaveThumb from "@/assets/environments/vermilion-thumb.jpg.asset.json";


/**
 * Environments.
 *
 * visionOS puts the interface in a place. Glass has nothing to refract without
 * one: over a flat fill the same material reads as grey plastic, so the scene
 * behind is load-bearing rather than decorative.
 *
 * The four shipped here are PLACEHOLDERS, generated by
 * scripts/generate-environments.py. To use real photography, drop files into
 * public/environments/ and edit this list - nothing else needs to change.
 * See docs/DESIGN-SYSTEM.md for sizing and tonal requirements.
 */

export interface EnvironmentDef {
  id: string;
  name: string;
  description: string;
  /** Served from public/environments/. */
  image: string;
  /** A 64px twin, inlined as the blurred first paint. */
  thumb: string;
  /** Which text colour the scene can carry. */
  theme: "dark" | "light";
}

export const ENVIRONMENTS: EnvironmentDef[] = [
  {
    id: "sonoma",
    name: "Sonoma",
    description: "Layered colour waves at sunset. Bright, graphic, dark type.",
    image: sonoma.url,
    thumb: sonomaThumb.url,
    theme: "light",
  },
  {
    id: "ventura",
    name: "Ventura",
    description: "Soft gradient bloom of magenta, blue and warm white.",
    image: ventura.url,
    thumb: venturaThumb.url,
    theme: "light",
  },
  {
    id: "mavericks",
    name: "Mavericks",
    description: "A long-lens wave rolling under a peach sunset.",
    image: mavericks.url,
    thumb: mavericksThumb.url,
    theme: "light",
  },
  {
    id: "el-capitan",
    name: "El Capitan",
    description: "Mist rising through pines below a granite face.",
    image: elCapitan.url,
    thumb: elCapitanThumb.url,
    theme: "light",
  },
  {
    id: "big-sur",
    name: "Big Sur",
    description: "Twilight over black sand and still water. The calmest to read against.",
    image: bigSur.url,
    thumb: bigSurThumb.url,
    theme: "dark",
  },
  {
    id: "catalina",
    name: "Catalina",
    description: "Winter dusk in the valley. Deep, cold, cinematic.",
    image: catalina.url,
    thumb: catalinaThumb.url,
    theme: "dark",
  },
  {
    id: "monterey",
    name: "Monterey",
    description: "Warm lamplight on the coast after sunset.",
    image: sierra.url,
    thumb: sierraThumb.url,
    theme: "dark",
  },
  {
    id: "mojave",
    name: "Mojave",
    description: "Red canyon walls under bright daylight. Pale sky, dark type.",
    image: mojave.url,
    thumb: mojaveThumb.url,
    theme: "light",
  },
];

/**
 * Big Sur: twilight over black sand, the calmest of the set to read against.
 *
 * The default is a dark scene on purpose. Apple's glass is a low-opacity white
 * film over a dark scrim - the white comes from the specular edge, not the
 * fill - so translucency, vibrancy and the rim light only read as glass when
 * there is depth behind them. Over a bright scene the same material flattens
 * into pale grey plastic. Anyone who prefers a light scene still has all eight
 * in the picker.
 */
const DEFAULT_ID = "big-sur";


const STORAGE_KEY = "vision-environment";

interface EnvironmentContextValue {
  environment: EnvironmentDef;
  setEnvironment: (id: string) => void;
}

const EnvironmentContext = createContext<EnvironmentContextValue>({
  environment: ENVIRONMENTS[0]!,
  setEnvironment: () => {},
});

export function useEnvironment() {
  return useContext(EnvironmentContext);
}

function resolve(id: string | null): EnvironmentDef {
  return ENVIRONMENTS.find((e) => e.id === id) ?? ENVIRONMENTS[0]!;
}

export function EnvironmentProvider({ children }: { children: ReactNode }) {
  const [id, setId] = useState(DEFAULT_ID);

  // Read after mount: the server has no way to know the preference, and
  // guessing would flash the wrong scene.
  useEffect(() => {
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY);
      if (stored) setId(resolve(stored).id);
    } catch {
      /* private mode - the default is fine */
    }
  }, []);

  const environment = resolve(id);

  // The theme follows the scene. A dark environment cannot carry dark type.
  useEffect(() => {
    document.documentElement.classList.toggle("dark", environment.theme === "dark");
    document.documentElement.style.colorScheme = environment.theme;
  }, [environment.theme]);

  const setEnvironment = useCallback((next: string) => {
    setId(resolve(next).id);
    try {
      window.localStorage.setItem(STORAGE_KEY, next);
    } catch {
      /* nothing to do */
    }
  }, []);

  const value = useMemo(() => ({ environment, setEnvironment }), [environment, setEnvironment]);

  return (
    <EnvironmentContext.Provider value={value}>
      <Environment />
      {children}
    </EnvironmentContext.Provider>
  );
}

/**
 * The scene itself: a blurred thumbnail immediately, the full image once it
 * decodes, and a scrim that guarantees contrast whatever the photograph does.
 */
function Environment() {
  const { environment } = useEnvironment();
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    setLoaded(false);
    const img = new Image();
    img.src = environment.image;
    img.decode?.().then(
      () => setLoaded(true),
      () => setLoaded(true), // a decode failure still shows the thumb + scrim
    );
    if (img.complete) setLoaded(true);
  }, [environment.image]);

  return (
    <div className="environment" aria-hidden>
      <div
        className="environment__image"
        data-loaded="true"
        style={{ backgroundImage: `url(${environment.thumb})`, filter: "blur(28px)" }}
      />
      <div
        className="environment__image"
        data-loaded={loaded}
        style={{ backgroundImage: `url(${environment.image})` }}
      />
      <div className="environment__scrim" />
    </div>
  );
}

/** The picker, styled as a visionOS settings row. */
export function EnvironmentPicker({ className }: { className?: string }) {
  const { environment, setEnvironment } = useEnvironment();

  return (
    <div className={cn("space-y-2", className)}>
      <div className="flex items-center gap-2 px-1">
        <Mountain className="h-3.5 w-3.5 text-muted-foreground" />
        <span className="text-[0.7rem] font-medium uppercase tracking-[0.14em] text-muted-foreground">
          Environment
        </span>
      </div>

      <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
        {ENVIRONMENTS.map((env) => {
          const active = env.id === environment.id;
          return (
            <button
              key={env.id}
              type="button"
              onClick={() => setEnvironment(env.id)}
              aria-pressed={active}
              title={env.description}
              className={cn(
                "press focus-spatial group relative h-16 overflow-hidden rounded-2xl border text-left",
                active
                  ? "border-primary/70"
                  : "border-[var(--edge)] hover:border-[var(--edge-strong)]",
              )}
            >
              <span
                className="absolute inset-0 bg-cover bg-center transition-transform duration-500 group-hover:scale-110"
                style={{ backgroundImage: `url(${env.thumb})` }}
              />
              <span className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
              <span className="absolute inset-x-0 bottom-0 flex items-center justify-between px-2.5 py-1.5">
                <span className="text-[0.7rem] font-medium text-white drop-shadow">{env.name}</span>
                {active && (
                  <span className="flex h-4 w-4 items-center justify-center rounded-full bg-primary">
                    <Check className="h-2.5 w-2.5 text-primary-foreground" strokeWidth={3} />
                  </span>
                )}
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

/**
 * The environment control, as it appears in the window chrome. visionOS keeps
 * this in Control Center rather than inside an app's navigation, so it lives
 * beside the account rather than in the ornament.
 */
export function EnvironmentButton() {
  const { environment } = useEnvironment();

  return (
    <Popover>
      <PopoverTrigger asChild>
        <button
          type="button"
          title={`Environment: ${environment.name}`}
          aria-label={`Change environment. Currently ${environment.name}.`}
          className="press focus-spatial flex h-8 items-center gap-2 rounded-full border border-[var(--edge)] bg-[var(--mat-thin)] pl-1.5 pr-3 transition-colors hover:bg-[var(--mat-regular)]"
        >
          <span
            className="h-5 w-5 shrink-0 rounded-full bg-cover bg-center ring-1 ring-inset ring-white/25"
            style={{ backgroundImage: `url(${environment.thumb})` }}
          />
          <span className="hidden text-[0.72rem] text-muted-foreground md:block">
            {environment.name}
          </span>
        </button>
      </PopoverTrigger>
      <PopoverContent align="end" className="w-72 p-3">
        <EnvironmentPicker />

      </PopoverContent>
    </Popover>
  );
}
